### ISSUE TITLE
[test-failure] Sanitizer builds, '_DEFAULT_SOURCE' macro redefined

### ISSUE THREAD

**Issue by zuiderkwast** [madolson/placeholderkv#1394]
The unit tests for networking.c were introduced in #1360. @uriyage can you take a look? Can it be solved by just reordering the includes?

* https://github.com/valkey-io/valkey/actions/runs/12170639212/job/33946009664
* https://github.com/valkey-io/valkey/actions/runs/12150400350/job/33883091510

```
In file included from unit/test_networking.c:3:
In file included from unit/../networking.c:30:
In file included from unit/../server.h:33:
unit/../fmacros.h:37:9: error: '_DEFAULT_SOURCE' macro redefined [-Werror,-Wmacro-redefined]
#define _DEFAULT_SOURCE
        ^
/usr/include/features.h:236:10: note: previous definition is here
# define _DEFAULT_SOURCE        1
         ^
In file included from unit/test_networking.c:3:
unit/../networking.c:2049:22: error: use of undeclared identifier 'IOV_MAX'
    int iovmax = min(IOV_MAX, c->conn->iovcnt);
                     ^
unit/../networking.c:2049:22: error: use of undeclared identifier 'IOV_MAX'
```
