### PR TITLE
Fix issues for older versions of Darwin and improve PowerPC support

### PR DESCRIPTION
**Pull request by barracuda156**
Existing code does not build on macOS < 10.7. There are two issues:
1. The check for `MAC_OS_10_6_DETECTED` does the opposite of what it should, since `AvailabilityMacros.h` does not define underscore-prefixed versions of macros. `__MAC_OS_X_VERSION_MAX_ALLOWED` evaluates to 0, and on 10.6 everything breaks down:
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_databases_valkey/valkey/work/compwrap/cc/opt/local/bin/clang-mp-11 -pedantic -DREDIS_STATIC='' -Wno-c11-extensions -std=gnu11 -Wall -W -Wno-missing-field-initializers -Werror=deprecated-declarations -Wstrict-prototypes -O3 -g -ggdb -arch x86_64 -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -I../deps/hdr_histogram -I../deps/fpconv -DUSE_JEMALLOC -I../deps/jemalloc/include -DUSE_OPENSSL=1 -I/usr/local/opt/openssl/include -DBUILD_TLS_MODULE=0 -MMD -o rdb.o -c rdb.c
replication.c:1666:21: error: 'fstat64' is deprecated [-Werror,-Wdeprecated-declarations]
                    redis_fstat(slave->repldbfd,&buf) == -1) {
                    ^
./config.h:50:21: note: expanded from macro 'redis_fstat'
#define redis_fstat fstat64
                    ^
/usr/include/sys/stat.h:463:35: note: 'fstat64' has been explicitly marked deprecated here
int     fstat64(int, struct stat64 *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5,__MAC_10_6,__IPHONE_NA,__IPHONE_NA);
                                      ^
/usr/include/Availability.h:137:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED'
                                                    __AVAILABILITY_INTERNAL##_macIntro##_DEP##_macDep
                                                    ^
<scratch space>:179:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_5_DEP__MAC_10_6
^
/usr/include/AvailabilityInternal.h:253:72: note: expanded from macro '__AVAILABILITY_INTERNAL__MAC_10_5_DEP__MAC_10_6'
        #define __AVAILABILITY_INTERNAL__MAC_10_5_DEP__MAC_10_6        __AVAILABILITY_INTERNAL_DEPRECATED
                                                                       ^
/usr/include/AvailabilityInternal.h:36:67: note: expanded from macro '__AVAILABILITY_INTERNAL_DEPRECATED'
#define __AVAILABILITY_INTERNAL_DEPRECATED         __attribute__((deprecated,visibility("default")))
                                                                  ^
1 error generated.
make[1]: *** [replication.o] Error 1
```
Credits to @mohd-akram who pointed out at possible origin of the this problem.

2. Once that is fixed, on 10.6 when building for `ppc` there are new errors, because the code uses inaccurate assumptions for archs. Fix that too.

### CODE REVIEW

**Comment by barracuda156** [comment]
1. There is no `eip` on PowerPC, but as I understood, the code defines some dummy function, so it is okay to keep? It was added in https://github.com/valkey-io/valkey/commit/0bf90d944313919eb8e63d3588bf63a367f020a3

2. Now sure how important is dumping all registers here. It is not implemented for other archs on BSD too. Perhaps, not bother with writing it for macOS? But if needed, that is doable.

**Comment by madolson** [comment]
> Now sure how important is dumping all registers here. It is not implemented for other archs on BSD too. Perhaps, not bother with writing it for macOS? But if needed, that is doable.

Nice to have, but definitely optional.

**Comment by madolson** [comment]
> Once that is fixed, on 10.6 when building for ppc there are new errors, because the code uses inaccurate assumptions for archs. Fix that too.

I assume you tested this on some old powerpc machine? I don't see a real way to validate this, so am sort of inclined to blindly trust this all works as expected. (I'm double checking all of the macro stuff, I can at least validate that :)

**Comment by barracuda156** [comment]
> > Once that is fixed, on 10.6 when building for ppc there are new errors, because the code uses inaccurate assumptions for archs. Fix that too.
> 
> I assume you tested this on some old powerpc machine? I don't see a real way to validate this, so am sort of inclined to blindly trust this all works as expected. (I'm double checking all of the macro stuff, I can at least validate that :)

Yes, tested on 10.6 ppc locally, and on buildbots x86 on 10.6 is fine now: https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/201844
It was failing originally: https://trac.macports.org/ticket/69887

**Review by madolson — APPROVED** [review]

**Comment by barracuda156** [comment]
@madolson Just for the record, there is one remaining issue not fixed here: https://github.com/valkey-io/valkey/issues/434
It is not specific to macOS though, but will affect all platforms on ppc and likely mips and arm.

In Macports we just fixed it manually from portfile code: https://github.com/macports/macports-ports/blob/00dcbe43592cfd6ffd312b5d5b017d703c9bb0b6/databases/valkey/Portfile#L60-L65
But if someone could fix a check for atomics, it would be nice. I believe, atomics issue should be reproducible on Linux 32-bit (at least ppc or arm, no idea about i386).

**Comment by madolson** [comment]
@barracuda156 Do you want this to be backported to our 7.2, or are you okay with it being fixed in future major/minor releases?

**Comment by barracuda156** [comment]
@madolson Thank you for merging!

> Do you want this to be backported to our 7.2, or are you okay with it being fixed in future major/minor releases?

If you plan a new release reasonably soon, I guess it is okay to wait. If timeline is unknown, maybe worth back porting. (Not many people are potentially affected by this, admittedly, but who knows, if someone tries to build it as is on < 10.7, it will not work.)

**Comment by madolson** [comment]
The next planned release is probably 3-4 months away. We haven't seen much of an ask for <10.6 builds, otherwise it would be have been pretty obvious it isn't working.

**Comment by barracuda156** [comment]
> The next planned release is probably 3-4 months away. We haven't seen much of an ask for <10.6 builds, otherwise it would be have been pretty obvious it isn't working.

That is expected, hardware is kinda scarce, and people got accustomed to a situation when everything is broken, so I guess seldom try. Since we have fixed this locally, carrying patches until the next release is no issue. So we are good with waiting. Thank you!
