### PR TITLE
Fix switch case compilation error in the new helloscripting

### PR DESCRIPTION
**Pull request by enjoy-binbin**
It is missing the curly braces.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
If there are local variables in a case, it's good to make it a scope. Is there a warning for that in some CI job?

**Review by zuiderkwast — APPROVED** [review]

**Comment by zuiderkwast** [comment]
I see the error in the daily runs: https://github.com/valkey-io/valkey/actions/runs/12449533103/job/34755280012

**Comment by zuiderkwast** [comment]
Introduced in #1277
