### PR TITLE
Fix build on 32-bit ARM by only using NEON on AArch64

### PR DESCRIPTION
**Pull request by leon-anavi**
Only enable `HAVE_ARM_NEON` on AArch64 because it supports vaddvq and all needed compiler intrinsics.

Fixes the following error when building for machine `qemuarm` using the Yocto Project and OpenEmbedded:

```
| bitops.c: In function 'popcountNEON':
| bitops.c:219:23: error: implicit declaration of function 'vaddvq_u16'; did you mean 'vaddq_u16'? [-Wimplicit-function-declaration]
|   219 |         uint32_t t1 = vaddvq_u16(sc);
|       |                       ^~~~~~~~~~
|       |                       vaddq_u16
| bitops.c:225:14: error: implicit declaration of function 'vaddvq_u8'; did you mean 'vaddq_u8'? [-Wimplicit-function-declaration]
|   225 |         t += vaddvq_u8(vcntq_u8(vld1q_u8(p)));
|       |              ^~~~~~~~~
|       |              vaddq_u8
```

More details are available in the following log: https://errors.yoctoproject.org/Errors/Details/889836/

### CODE REVIEW

**Review by zuiderkwast — APPROVED** [review]
Thank you!

This bug affects a subset of 32-bit ARM machines, right? `qemuarm` being one of them.

It's fine to skip NEON on all 32-bit arm. (I wonder if there is any way to do a runtime check for NEON though.)

**Comment by zuiderkwast** [comment]
@leon-anavi Do you know if this bug affects 8.1.4 also or only 9.0.0?

**Comment by leon-anavi** [comment]
> Thank you!
> 
> This bug affects a subset of 32-bit ARM machines, right? `qemuarm` being one of them.

Yes, exactly, it is a [machine configuration for running an ARMv7 system on QEMU](https://git.openembedded.org/openembedded-core/tree/meta/conf/machine/qemuarm.conf?h=master), so it is 32-bit.

The issues doesn't affect 64-bit ARMv8 machines like Raspberry Pi 5 which I typically use for testing.

**Comment by zuiderkwast** [comment]
Seems to be introduced in #2573, so it only affects 9.0.0 AFAICT.

**Comment by leon-anavi** [comment]
> Seems to be introduced in #2573, so it only affects 9.0.0 AFAICT.

Yes, version 8.1.4 is not affected. I've just built it successfully for `qemuarm`. Thank you for tracing the commit that have caused in on 32-bit ARM devices.

**Comment by leon-anavi** [comment]
@zuiderkwast thank you for the quick code review. In the openembedded development mailing list @kraj pointed out my patch limits the ARM Neon SIMD optimization in valkey to ARMv8 but there are 32-bit ARMv7 SoC with NEON.
 
I was wondering which machine could be used for testing. Maybe the Rockchip RK3288 SoC on the ASUS Tinker Board and Tinker Board S would be a good fit. I think I bought a Tinker Board for hobby projects many years ago but never really found the time to play with it. I will have to double-check and locate it.

 @zuiderkwast would it be beneficial for the community to explore this further and potentially add ARM NEON SIMD optimizations for 32-bit ARMv7 with NEON?

**Comment by zuiderkwast** [comment]
> @zuiderkwast would it be beneficial for the community to explore this further and potentially add ARM NEON SIMD optimizations for 32-bit ARMv7 with NEON?

Optimizing the 32-bit platforms is very low prio IMO. We should just make sure we don't break them. A build on qemuarm in our daily github builds would be good to have. It would prevent similar mistakes in the future.
